# ==========================================================================
# POSTGRESQL DBA LAB - CLIENT AUTHENTICATION FILE (pg_hba.conf)
# Purpose: Security privileges, IP subnet filtering, and SCRAM-SHA-256 auth
# ==========================================================================

# TYPE  DATABASE        USER            ADDRESS                 METHOD

# Local unix domain socket connections
local   all             all                                     scram-sha-256

# IPv4 local connections (Localhost & Lab Docker Subnet)
host    all             lab_admin       127.0.0.1/32            scram-sha-256
host    all             all             10.0.0.0/8              scram-sha-256
host    all             all             172.16.0.0/12           scram-sha-256
host    all             all             192.168.0.0/16          scram-sha-256

# Streaming Replication connections for Replica Standby nodes
host    replication     replicator      172.16.0.0/12           scram-sha-256

# Reject all unencrypted or unknown subnet connections
host    all             all             all                     reject
